### ISSUE TITLE
Don't thing values below freezing are working

### ISSUE THREAD

**Issue by GitRayman** [sparkfun/SparkFun_GridEYE_Arduino_Library#6]
Thanks for posting this driver.  I've adapted for the Propeller 2 MCU.
But, I think I see an error for negative temperature values (i.e, values below freezing)...
I've fixed it like this:
```
        // if temperature is negative, mask out the sign byte and 
        // make the float negative
        //temperature &= ~(1 << 11);
        //temperature = temperature * -1;
        temperature |= 0b1111 << 12;  //RJA fixed this
```

**Comment by PaulZC** [comment]
Hi @GitRayman ,

Apologies for the VERY slow reply!

Yes, correct, there was all kinds of badness going on with negative temperatures. I've corrected this in v1.0.2 - which will be released shortly.

Best wishes,
Paul
